# Global pipeline configuration
pipeline:
  name: "HPC ETL Pipeline"
  version: "1.0.0"
  
logging:
  level: "INFO"
  format: '%(asctime)s - %(levelname)s - %(message)s'
  file: "pipeline.log"
  
defaults:
  processing:
    max_workers: 4
    batch_size: 500000
    memory_limit_gb: 80
    temp_directory: "./temp"
    
  output:
    format: "parquet"
    compression: "snappy"
    
  validation:
    min_rows: 1
    max_file_size_gb: 10